apiVersion: v1
kind: Secret
metadata:
  name: k8s-sa-token
  namespace: actions
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-service-account
type: kubernetes.io/service-account-token
