apiVersion: v1
kind: Secret
metadata:
  name: aboba-backend-secret
  labels:
    app: aboba-backend
type: Opaque
stringData:
  POSTGRES_HOST: "postgres.dev"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "java_user"
  POSTGRES_PASSWORD: "1111"
  REDIS_HOST: "redis-master.dev"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "Uhsbp5jyDc"
  FLUENTD_ENABLED: "false"
  FLUENTD_HOST: "localhost"
  FLUENTD_PORT: "24224"
  SERVER_PORT: "8081"
  DEBUG: "true"
