apiVersion: v1
kind: Service
metadata:
  name: {{ include "aboba-backend.fullname" . }}
  labels:
    app: {{ include "aboba-backend.name" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: {{ include "aboba-backend.name" . }}
